### ISSUE TITLE
Single Panel and Icon View

### ISSUE THREAD

**Issue by dufferzafar** [MeanEYE/Sunflower#131]
I think these features would make sunflower a bit more like a traditional file manager (like nautilus etc.) but I don't always need the two panes, so I think an ability to hide the right one would be great.

I tried commenting this [line of code](https://github.com/MeanEYE/Sunflower/blob/develop/application/gui/main_window.py#L623), the right pane got hidden but sadly I got some weird errors when pressing enter on a directory:

```
/home/dufferzafar/dev/clones/Sunflower/application/plugins/file_list/file_list.py:318: GtkWarning: IA__gdk_screen_get_setting: assertion 'GDK_IS_SCREEN (screen)' failed
  int(gtk.Settings().get_property('gtk-font-name').split()[-1])
Traceback (most recent call last):
  File "/home/dufferzafar/dev/clones/Sunflower/application/plugins/file_list/file_list.py", line 339, in _control_got_focus
    ItemList._control_got_focus(self, widget, data)
  File "/home/dufferzafar/dev/clones/Sunflower/application/plugin_base/item_list.py", line 1291, in _control_got_focus
    PluginBase._control_got_focus(self, widget, data)
  File "/home/dufferzafar/dev/clones/Sunflower/application/plugin_base/plugin.py", line 198, in _control_got_focus
    self._parent.get_opposite_object(self).update_state(gtk.STATE_NORMAL)
  File "/home/dufferzafar/dev/clones/Sunflower/application/plugin_base/plugin.py", line 318, in update_state
    self._title_bar.set_state(state)
  File "/home/dufferzafar/dev/clones/Sunflower/application/widgets/title_bar.py", line 310, in set_state
    self.__apply_color()
  File "/home/dufferzafar/dev/clones/Sunflower/application/widgets/title_bar.py", line 258, in __apply_color
    self._breadcrumbs.apply_color(colors)
  File "/home/dufferzafar/dev/clones/Sunflower/application/widgets/breadcrumbs.py", line 202, in apply_color
    self._smart_color = self.__get_color(*colors)
TypeError: __get_color() argument after * must be a sequence, not NoneType
```
Any guess why this happened?

I also couldn't figure out how to change the view from list to icons.

I get that single pane/icon view is not what sunflower was created for, and may not be desired by many, but could please guide me what part of code I should be fiddling with, to make the changes for myself?

**Comment by MeanEYE** [comment]
Sunflower is built as twin-panel file manager and pretty much every part of the code assumes there are two panels. Colors in GTK are assigned one widget is "realized" or shortly after showing them. Breadcrumbs here assume panel is visible and try to get proper coloring.

Trying to make a single panel editor is kind of pointless considering how many out there already exist. Design with two panes is not something I came up with, it's pretty much a design from old command line only interfaced of the likes of Norton Command, DOS Navigator, Midnight Commander and others.

**Comment by dufferzafar** [comment]
I don't think there are a lot of file managers written in Python (except for [ranger](https://github.com/hut/ranger/)), so I was pretty excited to find this because I felt I could hack it suit my needs. 

I do like the twin pane design, no doubt. In many cases its pretty useful, but sometimes the second pane just is not needed so I thought maybe it could be hidden. 

It makes sense if you don't want this feature since I am probably the first person who has had such needs.

What about the icon view?

**Comment by MeanEYE** [comment]
You are not the first person to ask for such feature. It's simply not possible to remove a panel at this stage of development. Whole user experience revolves around having 2 panels. Copying/moving works from one side to other etc. What I think can be done instead is to have sort of minimize option for one panel so it doesn't take a lot of space on screen until copy/move dialog is shown.

As for icon view, GTK is not all that simple in this context. These are two different widgets `gtk.TreeView` being default one. The one you speak of is `gtk.IconView`.

**Comment by dufferzafar** [comment]
Yeah, I don't care if it is removed/hidden - as long as I am not seeing it, it's fine, so having a minimize option would be great!

I'll try fiddling with `IconView`. Thanks!

**Comment by dufferzafar** [comment]
Hey! I totally wasn't aware the single pane issue had been created beore: #28 

I followed the 'Move to opposite panel' trick from there. :smile: 

I think this issue can be closed now.

**Comment by MeanEYE** [comment]
Well, if you'd like I can still implement the minimize feature. Concept remains the same, in keeping two panes, but gives move screen space.

**Comment by dufferzafar** [comment]
Yeah, go for it, I'd say!
