### ISSUE TITLE
Cannot delete files from ntfs formatted partition

### ISSUE THREAD

**Issue by tmrd2513** [MeanEYE/Sunflower#184]
If i want to delete a file from a ntfs formatted partition i get an error message box without any message and the four options "abort | skip | skip all | retry" (no button works). This error occurs since 0.3 release.

/etc/fstab:
> UUID="<UUID>"            /mnt/<FOLDER>               ntfs    defaults,umask=007,gid=46       0       0

strace output:
>Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/sunflower/application/operation.py", line 1516, in run
    remove_method(item)
  File "/usr/share/sunflower/application/operation.py", line 1473, in _trash_path
    response = self._get_trash_error_input(error)
  File "/usr/share/sunflower/application/operation.py", line 380, in _get_trash_error_input
    dialog = QuestionOperationError(self._application)
  File "/usr/share/sunflower/application/gui/input_dialog.py", line 1517, in __init__
    button_no.set_label(_('No'))
AttributeError: 'NoneType' object has no attribute 'set_label'

**Comment by MeanEYE** [comment]
Thanks for reporting this issue. I'll check if I can reproduce.

**Comment by tmrd2513** [comment]
FYI: This error does not occur in 0.2 (59).

**Comment by MeanEYE** [comment]
Oh, nice. That is important difference. Thanks!

**Comment by cmallwitz** [comment]
I don't think this is a NTFS issue but a problem with an unhandled error. Based on the trace back above this has been fixed by PR #213

Issue can be closed.

**Comment by MeanEYE** [comment]
That's the last release. I should probably release a bugfix version but at the moment am focusing on GTK3 version which I'd like to release as soon as possible.

**Comment by MeanEYE** [comment]
Considering my previous answer didn't really answer anything. I plan on dedicating more time these days to get new version out and running. At which point I will start closing all these PR's so I can complete migration to GitLab.

**Comment by Devligue** [comment]
Thank you. Appreciate it

**Comment by MeanEYE** [comment]
You are welcome.
