### ISSUE TITLE
Tree expander does not working using the mouse

### ISSUE THREAD

**Issue by tmrd2513** [MeanEYE/Sunflower#186]
Clicking on the tree expander with the mouse does not work. Every column shows '0'.
Using the keyboard does work.

strace output:
> /usr/share/sunflower/application/gui/main_window.py:1895: GtkWarning: Don't know color `0'
  gtk.main()
Traceback (most recent call last):
  File "/usr/share/sunflower/application/widgets/emblems_renderer.py", line 59, in do_render
    if not self.is_link and (self.emblems is None or len(self.emblems) == 0):
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "/usr/share/sunflower/application/widgets/emblems_renderer.py", line 59, in do_render
    if not self.is_link and (self.emblems is None or len(self.emblems) == 0):
TypeError: object of type 'int' has no len()

**Comment by MeanEYE** [comment]
This is strange. Can you please provide version on which this is happening?

**Comment by tmrd2513** [comment]
Sorry, i forgot this. It's in the newest release 0.3 (61).

**Comment by MeanEYE** [comment]
Okay, thanks. I'll check.

**Comment by adrinux** [comment]
Also seeing this with 0.3 (61) on Ubuntu Gnome 16.04 - in my case even the keyboard doesn't work, all I see is 0.

**Comment by MeanEYE** [comment]
Thanks for feedback.

**Comment by rhssk** [comment]
Same issue. 0.3 (61) on Arch Linux. Keyboard works fine but using mouse shows just 0.

**Comment by joshas** [comment]
@MeanEYE Cannot reproduce issue. Clicking on tree expander with mouse works without errors in develop branch.

**Comment by MeanEYE** [comment]
It probably has to do with the code that got removed during transition. I'll leave it open in case it reappears.
