### ISSUE TITLE
GTK3 - Opening files with key F4 fails if filename contains non ASCII characters

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#217]
Way to reproduce: create an empty file e.g. called привет.txt, open Sunflower, go to file and press F4

If I do this on latest branch develop I get:
Traceback (most recent call last):
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/accelerator_group.py", line 93, in _handle_activate
    result = callback_method(widget, label)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugins/file_list/file_list.py", line 1547, in _edit_selected
    self._parent.associations_manager.edit_file(selection_list)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/associations.py", line 247, in edit_file
    exec_string = self.__format_command_string(selection, command)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/associations.py", line 77, in __format_command_string
    exec_string = exec_string.replace('%U', ' '.join(uri_list))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 34: ordinal not in range(128)

On previous releases it just works, in both cases I'm starting Sunflower from the same terminal window just in a different directory.

Setting a break point at the offending line, the difference seems to be that in previous releases sys.getdefaultencoding() returns 'utf-8' which allows python to handle the non ASCII file name (which is stored in a string object - not a Unicode object - and encoded in UTF-8) correctly.

On the latest  development branch, sys.getdefaultencoding() is None (defaulting to 'ascii') and causes the issue reported.

An initial search didn't point to any obvious difference in the way Sunflower is launched. The only thing I could think of is something pygtk is doing and then I found this:

https://github.com/exaile/exaile/wiki/PyGI-migration-tasklist-%28GTK3-GStreamer-1.x%29#encoding-issues

We clearly rely on this to be in place - it makes total sense to me with GTK3 passing around utf-8 encoded strings and all but setting the default encoding programmatically to utf-8 seems to be discouraged:

http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

I still think we should do:
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

I tried this in main.py and it fixed the issue.

Discuss! :-)

**Comment by cmallwitz** [comment]
Resolved
