### ISSUE TITLE
Development version does not run on OpenSUSE 13.2

### ISSUE THREAD

**Issue by beschrade** [MeanEYE/Sunflower#218]
Unchanged development branch:

...> ./Sunflower.py
Traceback (most recent call last):
  File "./application/main.py", line 41, in on_activate
    from gui.main_window import MainWindow
  File "/daten/wrk/sunflw/Sunflower/application/gui/main_window.py", line 19, in <module>
    from associations import AssociationManager
  File "/daten/wrk/sunflw/Sunflower/application/associations.py", line 12, in <module>
    from plugin_base.terminal import TerminalType
  File "/daten/wrk/sunflw/Sunflower/application/plugin_base/terminal.py", line 4, in <module>
    gi.require_version('Vte', '2.90')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available

After commenting out "gi.require_version('Vte', '2.90')"

...> ./Sunflower.py
Traceback (most recent call last):
  File "./application/main.py", line 41, in on_activate
    from gui.main_window import MainWindow
  File "/daten/wrk/sunflw/Sunflower/application/gui/main_window.py", line 19, in <module>
    from associations import AssociationManager
  File "/daten/wrk/sunflw/Sunflower/application/associations.py", line 12, in <module>
    from plugin_base.terminal import TerminalType
  File "/daten/wrk/sunflw/Sunflower/application/plugin_base/terminal.py", line 7, in <module>
    from gi.repository import Gtk, Gdk, Vte, GConf
ImportError: cannot import name Vte

Starting Python in interactive mode and trying to import Vte results in "Cannot import". So Vte seems to not be present with Gtk3.

Removing the import of Vte results in Sunflower running OK.  My opinion: I could do without Vte and suggest changing the button to start an external terminal. Vte will not be present in distros for a long time which will result in Sunflower being unusable for the standard user.

**Comment by MeanEYE** [comment]
Hm, `Vte` should be optional. When was this OS version released? Thanks or reporting this issue.

**Comment by beschrade** [comment]
OpenSUSE 13.2 was released in november 2014. Module python-vte is installed. Current master works fine including vte. Looks like vte for gtk2 is available and installed, but vte for gtk3 is not in gi.repository. The current OpenSUSE version uses the same version of python-vte, so i would expect it to behave the same.

**Comment by MeanEYE** [comment]
Development version uses GObject Introspection. Which means you need to have `gir` resource installed for Vte. On Debian package name is something like `gir1.2-vte`. Individual Python modules are not used with `gi`.

**Comment by beschrade** [comment]
girepository-1_0 and libgirepository-1_0 are installed. The text of this packages says they provide the GObject introspection. I cannot find a vte-specific module for OpenSUSE in this context. Also: the rest of the import list (Gtk, Gdk, GConf) works fine. Looks to me like introspection is in place and works ok, just Vte is not present in a Gtk3 version.

Since i have this laptop which does not run i will try to look into solving it by making Vte optional and starting an external terminal instead.

Additionally i will check why the development version does not start on Ubuntu 12.04 LTS. I presume both problems to be caused by the switch to gtk3.

**Comment by MeanEYE** [comment]
I have the same guess. We did use to have a check if Vte was available or not. Ideally we should just switch to whichever is available. In case Vte package is not present, we can use `xterm` or something similar which supports embedding.
