### ISSUE TITLE
sunflower-0.3.61-1.all does not work on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nervgh** [MeanEYE/Sunflower#244]
``` bash
$ sunflower 
Traceback (most recent call last):
  File "/usr/share/sunflower/application/main.py", line 31, in <module>
    from gui.main_window import MainWindow
  File "/usr/share/sunflower/application/gui/main_window.py", line 31, in <module>
    from plugin_base.item_list import ItemList
  File "/usr/share/sunflower/application/plugin_base/item_list.py", line 11, in <module>
    from tools.viewer import Viewer
  File "/usr/share/sunflower/application/tools/viewer.py", line 2, in <module>
    import chardet
ImportError: No module named chardet
Failed running with python2.7
```

``` bash
$ python --version
Python 2.7.11+
```

**Comment by MeanEYE** [comment]
Package is missing dependency named `python-chardet`. If you install that package everything should work. Thanks for reporting I'll fix this issue on official package.

**Comment by nervgh** [comment]
Thank you for the Sunflower and your fast answer :v:

**Comment by MeanEYE** [comment]
You are welcome.

**Comment by joshas** [comment]
@MeanEYE This issue probably can be closed as fixed and obsolete after migration to Python3?

**Comment by MeanEYE** [comment]
Right you are @joshas .
