### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by Tetomte** [MeanEYE/Sunflower#249]
sunflower crash on start. What can i do?
screen:
Sunflower.py
Traceback (most recent call last):
  File "./Sunflower/application/main.py", line 31, in <module>
    from gui.main_window import MainWindow
  File "/home/paul/Sunflower/application/gui/main_window.py", line 31, in <module>
    from plugin_base.item_list import ItemList
  File "/home/paul/Sunflower/application/plugin_base/item_list.py", line 11, in <module>
    from tools.viewer import Viewer
  File "/home/paul/Sunflower/application/tools/viewer.py", line 2, in <module>
    import chardet
ImportError: No module named chardet
Failed running with python2.7

Thanks

**Comment by MeanEYE** [comment]
Sorry about that. It's a missing dependency in `deb` package. You need to install `python-chardet`. I should really update packages on site. Thanks for reporting!
