### ISSUE TITLE
Opening USB flash drive mount from bookmarks fails

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#360]
Plugged in USB flash drive. It correctly appears in Bookmarks, but clicking on it results in error:
````
Traceback (most recent call last):
  File "/home/virtualbox/dev/Sunflower/sunflower/widgets/location_menu.py", line 144, in __handle_open_click
    self._active_object.change_path(selected_location.get_location())
  File "/home/virtualbox/dev/Sunflower/sunflower/mounts.py", line 141, in get_location
    root.unref()
  File "/usr/lib64/python3.7/site-packages/gi/overrides/GObject.py", line 508, in _unsupported_method
    raise RuntimeError('This method is currently unsupported.')
RuntimeError: This method is currently unsupported.
````
Removing `root.unref()` from mounts.py line 141 fixes issue, but is it actually a valid fix? Won't this lead to memory leaks or other problems?

**Comment by MeanEYE** [comment]
Am not entirely sure it will cause memory leaks because `unref` should be automatically called upon object destruction by Python. Either way, removing this line and leaving `# TODO: Check for memory leaks` is better than this feature not working.
