### ISSUE TITLE
Unable to open directory after directory size calculation

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#361]
Press space over any directory. Wait until it finishes calculating directory size. After pressing `Enter` to open this directory error occurs and search dialog opens up:
````
Traceback (most recent call last):
  File "/home/virtualbox/dev/Sunflower/sunflower/accelerator_group.py", line 93, in _handle_activate
    result = callback_method(widget, label)
  File "/home/virtualbox/dev/Sunflower/sunflower/plugins/file_list/file_list.py", line 465, in _execute_selected_item
    self.change_path(os.path.join(self.path, name))
  File "/home/virtualbox/dev/Sunflower/sunflower/plugins/file_list/file_list.py", line 2291, in change_path
    self._parent.disk_usage.cancel_all_for_object(self)
  File "/home/virtualbox/dev/Sunflower/sunflower/tools/disk_usage.py", line 138, in cancel_all_for_object
    for key in self._stop_events.keys():
RuntimeError: dictionary changed size during iteration
````

**Comment by MeanEYE** [comment]
This is something that was probably changed in Python3. To be honest it's not the best solution and probably needs more work.
