### ISSUE TITLE
Find files functionality is broken

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#418]
Opening "Find files" dialog and trying to execute Basic search results in errors in terminal:
````
Exception in thread Thread-12:

Traceback (most recent call last):

  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner

    self.run()

  File "/usr/lib64/python3.8/threading.py", line 870, in run

    self._target(*self._args, **self._kwargs)

  File "/home/virtualbox/dev/Sunflower/sunflower/tools/find_files.py", line 230, in __find_files

    extension_list = list(map(lambda child: child.extension, children))

NameError: name 'children' is not defined

````

**Comment by MeanEYE** [comment]
That's odd. I tested find files and didn't run into this. Thanks I'll take a look.

**Comment by STEPHEN-GOLDBOROUGH** [comment]
I have the same issue and an identical track back:

**Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/sunflower/tools/find_files.py", line 230, in __find_files
    extension_list = list(map(lambda child: child.extension, children))
NameError: name 'children' is not defined** 

Linux Mint, xfce, python version 3.6.9 (this was a pip install, debian/apt install is version 3.6.7)

thanks a lot, Stephen

**Comment by MeanEYE** [comment]
Hm, I just ran into this problem today myself. This will have to get fixed ASAP.
