### ISSUE TITLE
sunflower development version doesn't run

### ISSUE THREAD

**Issue by insolor** [MeanEYE/Sunflower#420]
When I run it from the terminal it shows the following error:
```
~/Sunflower$ python3 -m sunflower
Traceback (most recent call last):
  File "/home/username/Sunflower/sunflower/__main__.py", line 165, in do_activate
    dont_load_plugins=self.arguments is not None and self.arguments.dont_load_plugins
  File "/home/username/Sunflower/sunflower/gui/main_window.py", line 352, in __init__
    self.locations = LocationMenu(self)
  File "/home/username/Sunflower/sunflower/widgets/location_menu.py", line 86, in __init__
    self._application.mount_manager.attach_location_menu(self)
  File "/home/username/Sunflower/sunflower/mounts.py", line 26, in attach_location_menu
    self._location_menu.add_location(Volume(self, volume))
  File "/home/username/Sunflower/sunflower/mounts.py", line 129, in __init__
    self._create_interface()
  File "/home/username/Sunflower/sunflower/mounts.py", line 201, in _create_interface
    self.__handle_change(self._volume)
  File "/home/username/Sunflower/sunflower/mounts.py", line 139, in __handle_change
    self._unmount_button.set_visible(mount and mount.can_unmount())
TypeError: Argument 1 does not allow None as a value
```
The error appears after commit c82d745c4280853387edc7b2fe2f83b74bc24fc9

System:   Kernel: 5.3.0-53-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic

**Comment by MeanEYE** [comment]
That's an odd one. Thanks I'll fix it.

**Comment by MeanEYE** [comment]
Just pushed fix to `develop` branch. Can you please check?

**Comment by insolor** [comment]
@MeanEYE ok, it seems to be working now. I'll check on my home computer later, but for now, I think I'll close the issue.

**Comment by MeanEYE** [comment]
Thank you. Let me know if you run into any issues.
