### ISSUE TITLE
Unable to open remote locations

### ISSUE THREAD

**Issue by jtojnar** [MeanEYE/Sunflower#443]
If I take the WebDAV URL from https://ajaxbrowser.com/ (replace `https` with `davs` with URI) and try to change path to that, it fails with:

```
(Sunflower:9504): Gtk-CRITICAL **: 22:55:57.633: gtk_list_store_set_sort_column_id: assertion 'header != NULL' failed
Traceback (most recent call last):
  File "/nix/store/vs2swfmhrfd1g964qgcc4arlzbs1waj4-sunflower-2020-07-03-unstable/lib/python3.8/site-packages/sunflower/plugin_base/item_list.py", line 1558, in custom_path_entry
    self.change_path(os.path.expanduser(response[1]))
  File "/nix/store/vs2swfmhrfd1g964qgcc4arlzbs1waj4-sunflower-2020-07-03-unstable/lib/python3.8/site-packages/sunflower/plugins/file_list/file_list.py", line 2298, in change_path
    provider = self.get_provider(path)
  File "/nix/store/vs2swfmhrfd1g964qgcc4arlzbs1waj4-sunflower-2020-07-03-unstable/lib/python3.8/site-packages/sunflower/plugin_base/item_list.py", line 1660, in get_provider
    result = self.create_provider(path, False)
  File "/nix/store/vs2swfmhrfd1g964qgcc4arlzbs1waj4-sunflower-2020-07-03-unstable/lib/python3.8/site-packages/sunflower/plugin_base/item_list.py", line 1588, in create_provider
    root_path = result.get_root_path(path)
  File "/nix/store/vs2swfmhrfd1g964qgcc4arlzbs1waj4-sunflower-2020-07-03-unstable/lib/python3.8/site-packages/sunflower/plugins/file_list/gio_provider.py", line 299, in get_root_path
    mount = Gio.File.new_for_commandline_arg(path).find_enclosing_mount()
gi.repository.GLib.Error: g-io-error-quark: The specified location is not mounted (16)
```

If I mount it in Nautilus first, it works.

**Comment by jtojnar** [comment]
Yeah, this is an issue with system FTP bookmarks too.

**Comment by MeanEYE** [comment]
Good to know. I think I know where the issue is.

**Comment by asqwerth** [comment]
I am facing the same issue still with system FTP bookmarks as well as smb bookmarks.  In both cases, I am able to mount and open the locations with system file managers (e.g. Thunar) but when I click on the same location in the sunflower bookmark dropdown menu:
1. nothing happens for the smb bookmark.  
2. For the ftp bookmark, I get an error message popup saying that location "tp://[whatever]" cannot be found.  The bookmark is correctly set as "ftp://[whatever]" but based on the error message, sunflower sees the location with the first letter "f" missing.  

If I enter the ftp or smb location manually into the text field in the dropdown, nothing happens, the location isn't opened.

**Comment by MeanEYE** [comment]
Thank you for reporting this @asqwerth. I'll have a look and fix what needs fixing. Whole path code needs to be redone I feel. 
It's just too convoluted and issues of this kind keep popping up.

**Comment by PrzemekSkw** [comment]
Hello, how to remote connect to serwer with Sunflower? I don't see any option for that.

regards.
