### ISSUE TITLE
Sunflower fails to launch on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by dajare** [MeanEYE/Sunflower#446]
On my Ubuntu 18.04.5 LTS deskstop, I've installed `sunflower-0.4.62-2.all.deb`. Unfortuantely, it fails to launch. I tried from terminal and got this:

```
$ sunflower
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sunflower/__main__.py", line 165, in do_activate
    dont_load_plugins=self.arguments is not None and self.arguments.dont_load_plugins
  File "/usr/lib/python3/dist-packages/sunflower/gui/main_window.py", line 352, in __init__
    self.locations = LocationMenu(self)
  File "/usr/lib/python3/dist-packages/sunflower/widgets/location_menu.py", line 86, in __init__
    self._application.mount_manager.attach_location_menu(self)
  File "/usr/lib/python3/dist-packages/sunflower/mounts.py", line 26, in attach_location_menu
    self._location_menu.add_location(Volume(self, volume))
  File "/usr/lib/python3/dist-packages/sunflower/mounts.py", line 129, in __init__
    self._create_interface()
  File "/usr/lib/python3/dist-packages/sunflower/mounts.py", line 201, in _create_interface
    self.__handle_change(self._volume)
  File "/usr/lib/python3/dist-packages/sunflower/mounts.py", line 139, in __handle_change
    self._unmount_button.set_visible(mount and mount.can_unmount())
TypeError: Argument 1 does not allow None as a value
```

This looks like a very appealing file manager. I only wish I could use it!

**Comment by MeanEYE** [comment]
Thank you for reporting this. This issue has been fixed in newer version but I didn't apply it on older version. I have updated packed on site so you can reinstall and this issue should be fixed. Please let me know if there are any other issues.

**Comment by dajare** [comment]
Brilliant! Thanks for the swift reply, and good to know this was *already* fixed. ;)

I have now reinstalled, and all is indeed well.

**Comment by MeanEYE** [comment]
You are welcome. Please note that 0.4 version is still incomplete. It's between migrations from GTK2 to version 3. I planned on releasing more often but life got in way of things. 

However if you run into issues or feel something is missing please feel free to let me know. Even questions about where something is tell me whether features are too hidden or not.
