### ISSUE TITLE
Showing a main.css error on Void Linux

### ISSUE THREAD

**Issue by reback00** [MeanEYE/Sunflower#457]
Continuation from #453 . There is a message showing when I start sunflower on Void Linux:
```
$ sunflower
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sunflower/__main__.py", line 163, in do_activate
    self.window = MainWindow(
  File "/usr/lib/python3.8/site-packages/sunflower/gui/main_window.py", line 85, in __init__
    self._load_styles()
  File "/usr/lib/python3.8/site-packages/sunflower/gui/main_window.py", line 928, in _load_styles
    provider.load_from_file(Gio.File.new_for_path(file_name))
gi.repository.GLib.Error: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /bin/styles/main.css: No such file or directory (2)
```

I'm trying with this template:
```bash
# Template file for 'sunflower'
pkgname=sunflower
version=0.4
revision=1
_version_append_revision="-62"
wrksrc="Sunflower-${version}${_version_append_revision}"
build_style=python3-module
make_install_args="--optimize=1 --skip-build"
hostmakedepends="libnotify python3-setuptools python3-gobject gtk+3-devel python3-chardet"
makedepends="vte3-devel"
depends="gtk+3 vte3 python3-gobject python3-chardet librsvg"
short_desc="Small, customizable dual-panel file manager with support for plugins"
maintainer="reback00 <reback00@protonmail.com>"
license="GPL-3.0-or-later"
homepage="https://sunflower-fm.org"
distfiles="https://github.com/MeanEYE/Sunflower/archive/${version}${_version_append_revision}.tar.gz"
checksum=76f6e16a8e2761a13cfde56c5ee3625afd7e7286942ef75d67eca65384214b14
python_version=3
```

It builds through setup.py using [this](https://github.com/void-linux/void-packages/blob/master/common/build-style/python3-module.sh) file. But the path to main.css seems not be detected correctly on Void Linux.

**Comment by reback00** [comment]
I tried the template today. And surprizingly enough the main.css error message is gone! Well, I've got no idea ([as before](https://github.com/MeanEYE/Sunflower/issues/453#issuecomment-705167992)) how the main.css error is not showing anymore. It has changed into this message now (please ignore the `Gtk-WARNING` message, it's related to the icon theme I'm using):

```
$ sunflower

(Sunflower:5585): Gtk-WARNING **: 03:29:38.365: Theme directory 48/mimetypes of theme Qogir has no size field

Warning: Unknown plugin class "FileList". Tab skipped!
Warning: Unknown plugin class "FileList". Tab skipped!
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sunflower/__main__.py", line 169, in do_activate
    self.window.create_tabs(self.arguments)
  File "/usr/lib/python3.8/site-packages/sunflower/gui/main_window.py", line 1420, in create_tabs
    DefaultList = self.plugin_classes['file_list']
KeyError: 'file_list'
```

The template is using 0.4-62 release archive. Also seeing empty panels and empty menu:

![sunflower-01](https://user-images.githubusercontent.com/51861250/95390305-fb00db80-0916-11eb-8a39-9716523fc641.png)

**Comment by MeanEYE** [comment]
Empty panels are a result of an error occurring inside of `file_list` plugin. Hence unknown plugin class message.

**Comment by reback00** [comment]
I see. Is there any way this can be patched/fixed on 0.4-62?

**Comment by MeanEYE** [comment]
We need to see what the error is first. Whatever caused issue for FileList not to load needs to be fixed first. It's not a CSS issue.
