### ISSUE TITLE
File list is blank

### ISSUE THREAD

**Issue by amitbha** [MeanEYE/Sunflower#509]
Version: 0.5 (63)
Can't show some files sometimes, which are not hidden files.

![0324-142939](https://user-images.githubusercontent.com/4060625/159867439-cf45b8a3-cc35-41d5-bc1a-a717e59e8668.png)

**Comment by MeanEYE** [comment]
Thanks for reporting this issue. This probably means there's some problem handling one of the file names or their attributes. Can you start Sunflower from terminal by typing `sunflower` and then navigating to that directory. There will most likely be an error there which will describe problems in detail.

Thanks!

**Comment by amitbha** [comment]
~~~bash
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sunflower/plugins/file_list/file_list.py", line 1637, in _flush_queue
    new_iter = self._store.append(parent, data)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 1276, in append
    return self._do_insert(parent, -1, row)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 1268, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 907, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 921, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3.10/site-packages/gi/overrides/GObject.py", line 208, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3.10/site-packages/gi/overrides/GObject.py", line 257, in set_value
    _gi._gvalue_set(self, py_value)
OverflowError: 2193885632 not in range -2147483648 to 2147483647
~~~

**Comment by MeanEYE** [comment]
Oh, this is a size conversion error. I wonder how this happened. I'll take a look. This seems odd.

**Comment by MeanEYE** [comment]
@amitbha can you please test if this issue still exists now that potential fix has been merged?

**Comment by amitbha** [comment]
I think it's solved.

**Comment by MeanEYE** [comment]
That's good to know. Please reopen should your issue repeat itself.
