### ISSUE TITLE
Exception if copy/move a file to dictionary where same file already exists.

### ISSUE THREAD

**Issue by multiSnow** [MeanEYE/Sunflower#84]
path in left:
dir1/file
path in right:
dir2/file

copy/move file from left to right raise:
```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/sunflower/application/operation.py", line 1194, in run
    self._copy_file_list()
  File "/usr/share/sunflower/application/operation.py", line 918, in _copy_file_list
    self._copy_file(file_name, source_path)
  File "/usr/share/sunflower/application/operation.py", line 767, in _copy_file
    self._file_list.pop(self._file_list.index(file_name))
ValueError: 'file' is not in list
```

and the process window keep showing there with doing nothing.

checkbox with:
```
Set date and time on destination
Silent Mode
  Merge directories
```

using develop bench

**Comment by MeanEYE** [comment]
Okay, thanks. Confirmed it.

**Comment by MeanEYE** [comment]
@ArseniyK is working on fix for this issue.
