### ISSUE TITLE
Exception when copying a file to a google mounted drive

### ISSUE THREAD

**Issue by tiberiuichim** [MeanEYE/Sunflower#88]
This is the exception:

    Exception in thread Thread-17:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/share/sunflower/application/operation.py", line 1179, in run
        self._copy_file_list()
      File "/usr/share/sunflower/application/operation.py", line 906, in _copy_file_list
        self._copy_file(file_)
      File "/usr/share/sunflower/application/operation.py", line 861, in _copy_file
        dh.close()
    IOError: [Errno 16] Device or resource busy

Expected behaviour: automatically retry operation.

**Comment by MeanEYE** [comment]
Can you tell me what's the destination device or service? This has never occurred until now and I'd like to know in which cases does destination device become busy.

**Comment by tiberiuichim** [comment]
The destination device is a location mounted with google-drive-fuse-ocaml.

**Comment by tiberiuichim** [comment]
This was with the latest provided ubuntu deb file, I've cloned this repo and I'm trying now with this development version, I saw that there are some code changes

**Comment by MeanEYE** [comment]
How does Nautilus handle this issue? Retrying automatically on this error doesn't seem to be a good idea as it's raised as exception. If we should retry, then internal FUSE plugin should have implemented some sort of buffering to mitigate issues of this kind.

**Comment by MeanEYE** [comment]
There are indeed code changes. Nothing related to this I think. But give it a shot.

**Comment by tiberiuichim** [comment]
Note: I'm not saying it's the problem with Sunflower, as I have got the same issue with midnight commander, just that sunflower should handle the issue. Right now the opened window with the operation is locked, it's not even possible to close it.

**Comment by tiberiuichim** [comment]
Ideally it would provide a "always retry on errors" on copy/move operations. If there's an error, the current job (the file where the error was triggered) would be retried.

**Comment by MeanEYE** [comment]
Hm, so the issue here is closing destination file. Hm. Okay, I'll accept this issue and rename it. Thanks for reporting.
